version: '3.1'
services:
    shop-db:
        image: mysql:5.7.22
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - 8989:3306
        volumes:
            - "./data/db/mysql:/var/lib/mysql"

    adminer:
        image: adminer
        ports:
            - 8181:8080

