# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:6.7.0

RUN sysctl -w vm.max_map_count=262144


# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu

#RUN elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.9/elasticsearch-analysis-morphology-5.6.9.zip
