version: '3.1'
services:
  db:
    image: postgres:11.1
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - "./data/db/postgres:/var/lib/postgresql/data"
      - "./conf/postgresql.conf:/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - "./data/pgdata:/root/.pgadmin"
    ports:
      - 8182:80
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
